version: "3.8"

services:
  wms-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: wms-app
    volumes:
      - .:/var/www/html:delegated
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    restart: unless-stopped
    tty: true