version: "3.8"

services:
  wms-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: wms-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - REDIS_HOST=127.0.0.1
    restart: always
    # network_mode: "host"
