version: "3.8"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/conf/nginx.prod.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wms-app-1
      - wms-app-2
    networks:
      - app-network

  wms-app-1:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: wms-app-1
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=production
      - DB_HOST=wms.cb664q2s0ql0.ap-southeast-2.rds.amazonaws.com
      - DB_PORT=3306
      - REDIS_HOST=127.0.0.1
    restart: always
    networks:
      - app-network

  wms-app-2:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: wms-app-2
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=production
      - DB_HOST=wms.cb664q2s0ql0.ap-southeast-2.rds.amazonaws.com
      - DB_PORT=3306
      - REDIS_HOST=127.0.0.1
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
