version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: wms-app
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
    environment:
      - APP_ENV=production
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: wms-redis
    restart: unless-stopped
