worker_processes auto;

events {
    worker_connections 1024;
}

http {
    upstream laravel {
        zone laravel 64k;
        server wms-app:9000;
    }

    server {
        listen 80;
        server_name yourdomain.com;

        # Allow Let's Encrypt challenge requests
        location /.well-known/acme-challenge/ {
            root /var/www/public;
        }

        # Redirect all HTTP -> HTTPS
        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name yourdomain.com;

        # SSL Certificates
        ssl_certificate     /etc/letsencrypt/live/yourdomain.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/yourdomain.com/privkey.pem;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        root /var/www/public;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            include fastcgi_params;
            resolver 127.0.0.11 ipv6=off;    # Docker DNS
            fastcgi_pass laravel;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $realpath_root;
        }

        location ~ /\.ht {
            deny all;
        }
    }
}
