upstream laravel_backend {
    server wms-app-1:9000;
    server wms-app-2:9000;
}

# no https yet for production server

server {
    listen 80;
    # server_name yourdomain.com www.yourdomain.com;
    server_name ec2-3-27-44-87.ap-southeast-2.compute.amazonaws.com;

    root /var/www/html/public;
    index index.php;

    # location / {
    #    return 301 https://$host$request_uri;
    # }
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass laravel_backend;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }
}

# server {
#     listen 443 ssl;
    # server_name yourdomain.com www.yourdomain.com;
    # replace _ with the domain name later
    # server_name _;
#     server_name ec2-3-27-44-87.ap-southeast-2.compute.amazonaws.com;
#     root /var/www/html/public;

    # for https if domain is available
    # ssl_certificate /etc/letsencrypt/live/yourdomain.com/fullchain.pem;
    # ssl_certificate_key /etc/letsencrypt/live/yourdomain.com/privkey.pem;

#     index index.php;
    
#     location ^~ /.well-known/acme-challenge/ {
#         root /var/www/certbot;
#     }

#     location / {
#         try_files $uri $uri/ /index.php?$query_string;
#     }

#     location ~ \.php$ {
#         include fastcgi_params;
        # fastcgi_pass unix:/run/php/php-fpm.sock;  # ✅ use socket instead of 127.0.0.1:9000
#         fastcgi_pass laravel_backend;
#         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#     }

#     location ~ /\.ht {
#         deny all;
#     }
# }
