worker_processes auto;

events {
    worker_connections 1024;
}

http {
    upstream laravel {
        zone laravel 64k;
        server wms-app:9000;
    }

    server {
        listen 80;
        server_name _;

        root /var/www/public;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            include fastcgi_params;

            # Add Docker DNS resolver
            resolver 127.0.0.11 ipv6=off;
            
            # Pass to PHP-FPM
            fastcgi_pass laravel;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $realpath_root;
        }

        location ~ /\.ht {
            deny all;
        }
    }
}
