[supervisord]
nodaemon=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true

[program:octane-8000]
command=php artisan octane:start --server=swoole --host=127.0.0.1 --port=8000
autostart=true
autorestart=true
stdout_logfile=/var/www/storage/logs/octane-8000.log

[program:octane-8001]
command=php artisan octane:start --server=swoole --host=127.0.0.1 --port=8001
autostart=true
autorestart=true
stdout_logfile=/var/www/storage/logs/octane-8001.log

[program:octane-8002]
command=php artisan octane:start --server=swoole --host=127.0.0.1 --port=8002
autostart=true
autorestart=true
stdout_logfile=/var/www/storage/logs/octane-8002.log

[program:queue]
command=php artisan queue:work --sleep=3 --tries=3
autostart=true
autorestart=true
stdout_logfile=/var/www/storage/logs/queue.log

[program:cron]
command=cron -f
autostart=true
autorestart=true
